version: '2.2'
services:
    web:
        build:
            args:
                MOD: 'Debug'
        ports:
        - '0.0.0.0:5000:5000'
        environment:
            ASPNETCORE_URLS: 'http://+:5000'
            ASPNETCORE_ENVIRONMENT: 'Staging'
            APP_APP__DATABASE__HOST: 'postgres'
            APP_APP__DATABASE__DATABASE: 'MessageService'
            APP_APP__DATABASE__USERNAME: 'postgres'
            APP_APP__DATABASE__PASSWORD: 'Qwerty123!'
            APP_MESSAGING__TRANSPORT: 'RabbitMq'
            APP_MESSAGING__CONNECTIONURL: 'rabbitmq://rabbit'
            APP_MESSAGING__USERNAME: 'Manager'
            APP_MESSAGING__PASSWORD: 'Qwerty123!'
            APP_Debug__IsDebugMode: 'true'
        restart: on-failure
    postgres:
        ports:
          - '0.0.0.0:5432:5432'
        environment:
          POSTGRES_PASSWORD: 'Qwerty123!'
    jaeger:
        ports:
            - "5575:5575/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    rabbit:
        environment:
            RABBITMQ_DEFAULT_USER: 'Manager'
            RABBITMQ_DEFAULT_PASS: 'Qwerty123!'
            RABBITMQ_USE_LONGNAME: 'false'
            RABBITMQ_ERLANG_COOKIE: 'erlcookie'
            RABBIT_HOST: rabbit
            RABBITMQ_NODENAME: rabbit
        ports:
            - '0.0.0.0:4369:4369'
            - '0.0.0.0:5672:5672'
            - '0.0.0.0:5671:5671'
            - '0.0.0.0:15672:15672'
            - '0.0.0.0:15671:15671'
            - '0.0.0.0:25672:25672'
            - '0.0.0.0:35197:35197'